### PR TITLE
Feature: accordion section

### PR DESCRIPTION
**Pull request by palmfjord**
screenshot 2018-11-19 at 12 43 57

What do you say @isaacSennerholt, should we add the color variations directly?

### CODE REVIEW

**Comment by isaacSennerholt** [comment]
@palmfjord What are the cons of using colour variations right away?

**Comment by palmfjord** [comment]
@isaacSennerholt i guess it's just that i wanna keep the PR size down 🤷‍♀️ not sure how to implement the color thing exactly. Maybe we can merge this guy and i'll jump on switching colors in a separate pr?

**Comment by palmfjord** [comment]
@hedvigoscar @isaacSennerholt would you mind taking a second look btw? 🙈 i found some improvements after lunch break haha

**Comment by isaacSennerholt** [comment]
I think a "larger" PR size is fine as long as it isn't a bunch of complicated logic. But yea, i'm fine with you merging this one and you can do it in a separate :)

**Pull request merged**
